// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaugnpsywznsaznwwgjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdWducHN5d3puc2F6bnd3Z2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDE2MjIsImV4cCI6MjA3MzA3NzYyMn0.ykIbird2eGmN_ELS1nnVJDTMVmbM5orCWlQhvvoJITs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});